language: c
sudo: false


cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

matrix:
  fast_finish: true
  include:
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3 osx"
      os: osx

    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

    - env: BUILD=stack GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: BUILD=stack GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      compiler: ": #stack 8.0.2 osx"
      os: osx

  allow_failures:
    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3 osx"
      os: osx

    - env: BUILD=stack GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      compiler: ": #stack 8.0.2 osx"
      os: osx

    - env: BUILD=cabal CABALVER=head GHCVER=head

before_install:
 - unset CC
 - case "$BUILD" in
     stack)
       export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;;
     cabal)
       export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;;
   esac
 - ./.travis-setup.sh

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - case "$BUILD" in
     stack)
       stack bench;
       stack test --only-dependencies;;
     cabal)
       cabal --version;
       travis_retry cabal update;
       rm -f $(stack path --dist-dir)/stack-*.tar.gz;
       stack sdist --pvp-bounds=both;
       tar xf $(stack path --dist-dir)/stack-*.tar.gz --wildcards --strip-components=1 '*/stack.cabal';
       cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0;;
   esac

script:
 - case "$BUILD" in
     stack)
       stack --no-terminal test --haddock --no-haddock-deps;;
     cabal)
       cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror";
       cabal build;
       cabal test;
       cabal check;
   esac

